// @ts-nocheck
// This file is automatically generated. Do not modify it manually.

// Follow the instructions in the Firebase console to configure your app
// https://firebase.google.com/docs/web/setup
export const firebaseConfig = {
  apiKey: 'AIzaSyAiVGy0vlek9mplgUDhoCnaej--STTM02o',
  authDomain: 'studio-2880807235-e930f.firebaseapp.com',
  projectId: 'studio-2880807235-e930f',
  appId: '1:279761542213:web:7b350222e4c8e49ffc172c',
  messagingSenderId: '279761542213',
};
