// @ts-nocheck
// This file is automatically generated. Do not modify it manually.

// Follow the instructions in the Firebase console to configure your app
// https://firebase.google.com/docs/web/setup
export const firebaseConfig = {
  apiKey: 'AIzaSyD7a1gf69t9SwuInfaQFmL0tLi8KvYIIPA',
  authDomain: 'studio-5054114940-51b33.firebaseapp.com',
  projectId: 'studio-5054114940-51b33',
  appId: '1:426695686323:web:edf1e0c345149fb8e9d8c6',
  messagingSenderId: '426695686323',
};
